#!/bin/sh

# This step ask you to give a password for mysql root account.
yes | aptitude install mysql-server mysql-client libmysqlclient-dev 

yes | aptitude install curl screen vim emacs23-nox git-core build-essential zlib1g-dev libssl-dev libreadline5-dev imagemagick libmagickcore-dev libmagickwand-dev libxapian-dev libxapian15 xapian-tools  libxml2 libxml2-dev libxslt1-dev

# Install Ruby Enterprise Edition
rev=ruby-enterprise-1.8.7-2010.02
ruby_enterprise_url=http://rubyforge.org/frs/download.php/71096/ruby-enterprise-1.8.7-2010.02.tar.gz
nginx_rev=0.7.67

if [ ! -e /opt/$rev/bin/ruby ]; then
    if [ ! -e $rev.tar.gz ]; then
        wget $ruby_enterprise_url
    fi
    tar zxf $rev.tar.gz
    echo -e "\n/opt/$rev\n" | ./$rev/installer
fi

# update PATH
export PATH=/opt/$rev/bin:$PATH
echo "export PATH=/opt/$rev/bin:\$PATH" >> /etc/profile

# Update system gem if necessary
gem update --system
gem update

gem install passenger --no-ri --no-rdoc

# Install Nginx w/ Passenger. SSL-enabled.
if [ ! -e /opt/nginx/sbin/nginx ]; then
    wget -O /tmp/nginx-$nginx_rev.tar.gz http://nginx.org/download/nginx-$nginx_rev.tar.gz

    cd /tmp
    tar xzf nginx-$nginx_rev.tar.gz
    cd -

    echo -e "\n2\n/tmp/nginx-$nginx_rev\n\n--with-http_ssl_module\n\n\n" | passenger-install-nginx-module
fi

if [ ! -e /etc/init.d/nginx ]; then
    curl http://github.com/jnstq/rails-nginx-passenger-ubuntu/raw/master/nginx/nginx > /etc/init.d/nginx
    chmod +x /etc/init.d/nginx
fi

if [ ! -e /etc/logrotate.d/nginx ]; then
 echo '/usr/local/nginx/logs/*.log {\n
  daily\n
  missingok\n
  rotate 8\n
  compress\n
  delaycompress\n
  notifempty\n
  postrotate\n
    kill -USR1 `cat /opt/logs/nginx.pid`\n
  endscript\n
}' > /etc/logrotate.d/nginx
fi

# Create the user for rails apps
if [ ! -d /home/apps ]; then
    yes | adduser --quiet --disabled-password apps
fi

# Install massive number of ruby gems
if [ ! -f /home/apps/.gems_installed ]; then
    gem source -a http://gemcutter.org
    gem source -a http://gems.github.com

    gem install --no-ri --no-rdoc rmagick mysql ar_mailer sinatra datamapper do_sqlite3 do_mysql xspond-xapian-ruby ZenTest rspec rspec-rails factory_girl cucumber nokogiri mixology aws-s3 fastercsv icalendar newrelic_rpm webrat Selenium database_cleaner

    gem install --no-ri --no-rdoc rails 

    gem list --local > /home/apps/.gems_installed
fi
